export default {
	bgImage: require("../assets/Images/backgroundImage.jpg"),
	iconImage: require("../assets/Images/iconText.png"),
	checkCircle: require("../assets/Images/check-circle/ss.png"),
	bdParty: require("../assets/Images/BirthdayParty/3x.png"),
	foodClub: require("../assets/Images/FoodClub/3x.png"),
	frindSquad: require("../assets/Images/FriendsSquad/3x.png"),
	houseParty: require("../assets/Images/HouseParty/3x.png"),
	kittyChats: require("../assets/Images/KittyChats/3x.png"),
	pineAppleParty: require("../assets/Images/PineAppleParty/3x.png"),
	raveRoom: require("../assets/Images/RaveRoom/3x.png"),
	// bdParty: require("../assets/Images/"),
	// bdParty: require("../assets/Images/check-circle/ss.png"),
	// bdParty: require("../assets/Images/check-circle/ss.png"),
};
