export default {
	bgImage: require("../assets/Images/backgroundImage.jpg"),
	iconImage: require("../assets/Images/iconText.png"),
	checkCircle: require("../assets/Images/Logos/check-circle/ss.png"),
	bdParty: require("../assets/Images/Logos/BirthdayParty/3x.png"),
	foodClub: require("../assets/Images/Logos/FoodClub/3x.png"),
	frindSquad: require("../assets/Images/Logos/FriendsSquad/3x.png"),
	houseParty: require("../assets/Images/Logos/HouseParty/3x.png"),
	kittyChats: require("../assets/Images/Logos/KittyChats/3x.png"),
	pineAppleParty: require("../assets/Images/Logos/PineAppleParty/3x.png"),
	raveRoom: require("../assets/Images/Logos/RaveRoom/3x.png"),
	logo: require("../assets/Images/Logos/Logo/3x.png"),
	logo2: require("../assets/Images/Logos/Logo2/3x.png"),
	bdPartyPosters: require("../assets/Images/Posters/BirthdayParty/3x.png"),
	foodClubPosters: require("../assets/Images/Posters/FoodClub/3x.png"),
	frindSquadPosters: require("../assets/Images/Posters/FriendsSquad/3x.png"),
	housePartyPosters: require("../assets/Images/Posters/HouseParty/3x.png"),
	kittyChatsPosters: require("../assets/Images/Posters/KittyChats/3x.png"),
	pineApplePartyPosters: require("../assets/Images/Posters/PineAppleParty/3x.png"),
	raveRoomPosters: require("../assets/Images/Posters/RaveRoom/3x.png"),
	// bdParty: require("../assets/Images/check-circle/ss.png"),
	// bdParty: require("../assets/Images/check-circle/ss.png"),
};
